In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/Ecdat/Wages.csv"
df = pd.read_csv(url)

In [2]:
df.head()

,rownames,exp,wks,bluecol,ind,south,smsa,married,sex,union,ed,black,lwage
0,1,3,32,no,0,yes,no,yes,male,no,9,no,5.56068
1,2,4,43,no,0,yes,no,yes,male,no,9,no,5.72031
2,3,5,40,no,0,yes,no,yes,male,no,9,no,5.99645
3,4,6,39,no,0,yes,no,yes,male,no,9,no,5.99645
4,5,7,42,no,1,yes,no,yes,male,no,9,no,6.06146

In [3]:
df.describe()

,rownames,exp,wks,ind,ed,lwage
count,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000
mean,2083.000000,19.853782,46.811525,0.395438,12.845378,6.676346
std,1202.476264,10.966370,5.129098,0.489003,2.787995,0.461512
min,1.000000,1.000000,5.000000,0.000000,4.000000,4.605170
25%,1042.000000,11.000000,46.000000,0.000000,12.000000,6.395260
50%,2083.000000,18.000000,48.000000,0.000000,12.000000,6.684610
75%,3124.000000,29.000000,50.000000,1.000000,16.000000,6.952730
max,4165.000000,51.000000,52.000000,1.000000,17.000000,8.537000